name: CI Python

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps (requirements.txt)
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install test tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Lint (flake8) only if there are .py files
        id: lint
        run: |
          PY_FILES=$(git ls-files '*.py' | wc -l)
          if [ "$PY_FILES" -gt 0 ]; then
            echo "Found $PY_FILES Python files. Running flake8..."
            flake8 . --max-line-length=100
          else
            echo "No Python files. Skipping flake8."
          fi

      - name: Run tests only if tests exist
        if: hashFiles('tests/**/*.py') != ''
        run: pytest -q tests